name: ClaudeShelf
options:
  bundleIdPrefix: com.kjm
  deploymentTarget:
    macOS: "15.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  generateEmptyDirectories: false
  developmentLanguage: en

settings:
  base:
    SWIFT_VERSION: "6.0"
    SWIFT_STRICT_CONCURRENCY: complete
    MACOSX_DEPLOYMENT_TARGET: "15.0"

targets:
  ClaudeShelf:
    type: application
    platform: macOS
    sources:
      - path: ClaudeShelf
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.kjm.ClaudeShelf
        PRODUCT_NAME: ClaudeShelf
        INFOPLIST_FILE: ClaudeShelf/Info.plist
        CODE_SIGN_ENTITLEMENTS: ClaudeShelf/ClaudeShelf.entitlements
        CODE_SIGN_STYLE: Automatic
        COMBINE_HIDPI_IMAGES: true
        GENERATE_INFOPLIST_FILE: false
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

  ClaudeShelfTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: ClaudeShelfTests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: ClaudeShelf
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.kjm.ClaudeShelfTests
        GENERATE_INFOPLIST_FILE: true

schemes:
  ClaudeShelf:
    build:
      targets:
        ClaudeShelf: all
        ClaudeShelfTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - ClaudeShelfTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
