---
name: Jira PR Description

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  jira:
    uses: kevnm67/engineering-toolkit/.github/workflows/reusable-jira-description.yml@main
    secrets:
      JIRA_URL: ${{ secrets.JIRA_URL }}
      JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
